### ISSUE TITLE
Bug with Lost Legends class items

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#1199]
### Description of Problem or Question
@jubez187 recently made me aware of a bug with the lost legend classes. 

While using either the "soul reaper" or  the "elementalist" class in Valkyrie, there is a bug when opening the items panel, and their items are not shown.

In case you use the "elementalist" there will also be no way to close the item panel and Valkyrie will be stuck.

Steps to reproduce:
1. Start any Descent Scenario
2. Choose a mage hero with the "Elementalist" class and any other hero with any other class
3. As soon as it is possible open the item panel.

Screenshot:
![elementalist](https://user-images.githubusercontent.com/26790002/63538291-dcbffc80-c517-11e9-92f5-301c1a6a0542.jpg)

### Valkyrie Version
2.4.0.3

**Comment by NPBruce** [comment]
Fixed in 2.4.04

**Comment by DelphiDie** [comment]
Thanks for the quick fix Bruce. Just one minor thing: The Soul Reaper is still missing his "Mirror of Souls" starting item.

**Comment by NPBruce** [comment]
Raised as #1200
